Fixed several bugs, created a dummy code snippet
mike-live/llamba pull request #3
Opened 2024-07-26 10:59 UTC by SermanVS

2024-07-26 13:52 UTC, mike-live requested changes

2024-07-26 13:52 UTC, mike-live commented on README.md
> +class SampleBioAgeModel(nn.Module): pass
Вот тут не очевидно как пустая модель работает и что делает =)

2024-07-26 13:52 UTC, mike-live commented on README.md
> +connector = Connector(bioage_model=bioage_model, chat_model=chat_model)
Надо какое-то другое слово вместо connector/Connector. А то как-то из кода не ассоциируется с нужным действием. То есть слишком общее название, а в реальности оно очень узкое понятие обозначает

2024-07-26 13:52 UTC, mike-live commented on README.md
> +features = torch.rand(10, dtype=torch.float32)
Тут я бы 10 вынес в переменную, плюс ниже ещё есть она. А 10 это рандомное число или оно чем-то обусловлено?

2024-07-26 13:52 UTC, mike-live commented on samples/dummy.ipynb
> +      "h:\\Lobachevsky\\llamba\\llamba_env\\Lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stab
Этого тут не надо

2024-07-26 13:52 UTC, mike-live commented on samples/dummy.ipynb
> +   "execution_count": null,
Надо его запустить и показать что в выводе

2024-07-26 13:52 UTC, mike-live commented on requirements.txt
> +openpyxl
Вот это я не очень понял

2024-07-26 13:52 UTC, mike-live commented on llamba/connector.py
>          answer += 'You biological age is {age} and your aging acceleration is {acceleration}, which means '.format(age=round(data['bio_age'].values[0]), acceleration=round(acceleration[0]))
Лучше везде использовать bio_age или слитно bioage. Эта строка очень длинная и просится разбиться чтобы быть не длиннее 90 символов. И заодно f string

2024-07-26 13:55 UTC, SermanVS commented on README.md
> +class SampleBioAgeModel(nn.Module): pass
Так она пустышка специально...

2024-07-26 13:56 UTC, SermanVS commented on requirements.txt
> +openpyxl
Для семпла нужно. Там данные считываем из txai_omics_3, без него pandas не хочет работать

2024-07-26 13:57 UTC, SermanVS commented on llamba/connector.py
>          answer += 'You biological age is {age} and your aging acceleration is {acceleration}, which means '.format(age=round(data['bio_age'].values[0]), acceleration=round(acceleration[0]))
Тут f-string некрасиво будет, там имена параметров слишком длинные, сама строчка нечитаемой станет, но разобью чтоб короче было

2024-07-26 13:57 UTC, SermanVS commented on samples/dummy.ipynb
> +   "execution_count": null,
У пустышки пустой вывод, hence the name

2024-07-26 13:58 UTC, SermanVS commented on README.md
> +features = torch.rand(10, dtype=torch.float32)
Это рандомное число, которое ни на что не влияет. Просто пример типа "вот у нас условно 10 признаков"

2024-07-26 13:59 UTC, SermanVS commented on README.md
> +connector = Connector(bioage_model=bioage_model, chat_model=chat_model)
Я не знаю таких слов, которые могли бы описать четко смысл, при этом не превратившись в предложение

2024-08-09 09:04 UTC, mike-live requested changes
Предлагаю ещё в dummy.ipynb сверху сделать ячейку markdown с описанием того что тут вообще происходит.

2024-08-09 09:04 UTC, mike-live commented on llamba/connector.py
> +            .format(age=round(data['bio_age'].values[0]),
Напиши не age, а bioage. А то путает

2024-08-09 09:04 UTC, mike-live commented on llamba/connector.py
>  from llamba.chat_model import BaseModel
А почему она base model? Может ChatModel?

2024-08-09 09:04 UTC, mike-live commented on llamba/connector.py
> +        data['bio_age'] = self.bioage_model.inference(data=data.drop(['Age'], axis=1), device=device)
Транспонирование пропало, надеюсь это ок

2024-08-09 09:04 UTC, mike-live commented on llamba/bioage_model.py
> +    def inference(self, device: torch.device, data: pd.DataFrame):
Перестань параметры местами

2024-08-09 09:04 UTC, mike-live commented on llamba/bioage_model.py
> +            res = self.model(torch.from_numpy(data.values)).cuda().detach().numpy().ravel()
Скорее всего это не будет работать. Надо тестить. Сейчас input не на cuda и модель не на cuda. Возможно что-то ещё не на ней. В общем это не так изи обычно

2024-08-09 09:08 UTC, SermanVS commented on llamba/connector.py
> +        data['bio_age'] = self.bioage_model.inference(data=data.drop(['Age'], axis=1), device=device)
Да, оно ломало все

2024-08-09 09:09 UTC, SermanVS commented on llamba/bioage_model.py
> +            res = self.model(torch.from_numpy(data.values)).cuda().detach().numpy().ravel()
Модель парой строк выше закидывается на девайс.
Ну с данными потом потещу

2024-08-09 10:08 UTC, merged