Moved wrappers & added Ollama support
mike-live/llamba pull request #5
Opened 2024-08-22 19:24 UTC by SermanVS

2024-08-24 12:52 UTC, mike-live requested changes

2024-08-24 12:52 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +    def __init__(self, model: str, url="http://127.0.0.1:11434/api/generate"):
Хост и путь отделить на 2 переменные

2024-08-24 12:52 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +    def query(self, prompt: str,
Может вынесем query как вспомогательную функцию из chatbasemodel и отсюда? Вроде они одно и тоже делают

2024-08-24 12:52 UTC, mike-live commented on pyproject.toml
> +torc = "*"
Что за либа такая?

2024-08-24 12:52 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +            data_input[parameter] = kwargs.get(parameter, None)
Непонятно зачем get, он путает

По идее ты хотел сказать 
data_input |= kwargs

Либо ты хотел перебирать data_input, а не kwargs. Наверное второе даже логичнее

2024-08-24 12:52 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +            if response.status_code != 200:
Не хочешь для констант поиспользовать http.HTTPStatus? https://docs.python.org/3/library/http.html#http.HTTPStatus

2024-08-24 12:52 UTC, mike-live commented on pyproject.toml
> +[tool.poetry.dependencies]
Да ладно ка, ты смог poetry настроить вместо pip?

2024-08-24 12:52 UTC, mike-live commented on samples/immunoage_meet_ollama.ipynb
> +    "This example assumes that you have an Ollama model running (with `ollama serve`) on some host that is reachable (whether a `localhost` of your computer or some other host with public IP)."
Добавь тут ссылку на то что надо запустить или на инструкцию ollama

2024-08-24 12:52 UTC, mike-live commented on tests/test_functions.py
> +from llamba.chatmodel_wrappers.chatbase import ChatbaseModel
Может модуль будет просто chatmodels?

2024-08-24 12:52 UTC, mike-live commented on tests/test_functions.py
>  # Possible workaround -- self-hosted test runner
Тут имелось ввиду для chatbase именно или в смысле ollama? Возможно коммент устарел

2024-08-24 12:58 UTC, SermanVS commented on llamba/chatmodel_wrappers/ollama.py
> +    def query(self, prompt: str,
Можно описать такое поведение в абстрактном классе, чтобы в каком-нибудь другом случае можно было переопределить функцию, мало ли специфика какая-то будет

2024-08-24 13:01 UTC, SermanVS commented on llamba/chatmodel_wrappers/ollama.py
> +            data_input[parameter] = kwargs.get(parameter, None)
Тут логика такая, что в query можно передать доп параметрами что-то, которые потом улетят в JSON вместе с запросом. Но в текущей реализации это не будет работать. Наверное сделаем какой-то класс типа AdditionalParameters, объект которого можно будет прокидывать в query и там его раскрывать и в JSON записывать что-то

2024-08-24 13:02 UTC, SermanVS commented on llamba/chatmodel_wrappers/ollama.py
> +            if response.status_code != 200:
Это копипаста из нашего кода с Chatbase :)

2024-08-24 13:02 UTC, SermanVS commented on pyproject.toml
> +[tool.poetry.dependencies]
Ага, и мне даже понравилось)

2024-08-24 13:22 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +            data_input[parameter] = kwargs.get(parameter, None)
Если это не будет работать может тогда потрем?

2024-08-24 13:23 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +    def query(self, prompt: str,
Например да

2024-08-24 13:23 UTC, SermanVS commented on llamba/chatmodel_wrappers/ollama.py
> +            data_input[parameter] = kwargs.get(parameter, None)
Ага, уже выпилил

2024-08-24 13:23 UTC, mike-live commented on llamba/chatmodel_wrappers/ollama.py
> +            if response.status_code != 200:
Ну вот приведешь в порядок, заодно без копипасты

2024-11-27 14:24 UTC, mike-live requested changes
И видимо ещё надо описать где-то про shap_dict, а то не ясно, что в нем хранится должно, если я сам свою модельку придумаю.

2024-11-27 14:24 UTC, mike-live commented on llamba/chatmodels/ollama.py
> +            "num_threads": self.num_threads
По идее не так, а вот так:
```python
"options": {
    "num_threads": self.num_threads,
},
```

2024-11-27 14:24 UTC, mike-live commented on llamba/chatmodels/ollama.py
> +    def query(self, prompt: str, timeout=60):
Тут чет конфликт, не использованный параметр timeout

2024-11-27 14:24 UTC, mike-live commented on pyproject.toml
> +priority = "supplemental"
supplemental -> explicit

2024-11-27 14:24 UTC, mike-live commented on llamba/chatmodels/ollama.py
> +    def __init__(self, model: str, url="http://127.0.0.1:11434/", endpoint="api/generate", num_threads=1, check_connection_timeout=60, request_timeout=60):
В несколько строк

2024-11-30 11:17 UTC, mike-live approved these changes

2024-11-30 12:30 UTC, merged